spring.application.name=project-management
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/project_management?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

openai.api.key=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